language: python

# Use Travis's shiny new Docker infrastructure
# should result in faster build times
sudo: false

env:
    - TOXENV=py27
    - TOXENV=py33
    - TOXENV=py34
    - TOXENV=pypy

install:
    - travis_retry pip install tox

script:
    - travis_retry tox
